"""add pluggable encryption method key storage

Revision ID: 3982169f58ee
Revises: fd441732ee52
Create Date: 2026-09-17 11:26:52.846538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3982169f58ee'
down_revision: Union[str, Sequence[str], None] = 'fd441732ee52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public_key_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_keys_conversation_id'), 'conversation_keys', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_keys_id'), 'conversation_keys', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_keys_user_id'), 'conversation_keys', ['user_id'], unique=False)
    op.create_table('user_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('public_key_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'method', name='uq_user_keys_user_id_method')
    )
    op.create_index(op.f('ix_user_keys_id'), 'user_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_keys_method'), 'user_keys', ['method'], unique=False)
    op.create_index(op.f('ix_user_keys_user_id'), 'user_keys', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('domain_params_json', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('ciphertext_for_sender', sa.String(), nullable=True))
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('content', new_column_name='ciphertext')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('ciphertext', new_column_name='content')
    op.drop_column('messages', 'ciphertext_for_sender')
    op.drop_column('messages', 'conversation_id')
    op.drop_column('conversations', 'domain_params_json')
    op.drop_index(op.f('ix_user_keys_user_id'), table_name='user_keys')
    op.drop_index(op.f('ix_user_keys_method'), table_name='user_keys')
    op.drop_index(op.f('ix_user_keys_id'), table_name='user_keys')
    op.drop_table('user_keys')
    op.drop_index(op.f('ix_conversation_keys_user_id'), table_name='conversation_keys')
    op.drop_index(op.f('ix_conversation_keys_id'), table_name='conversation_keys')
    op.drop_index(op.f('ix_conversation_keys_conversation_id'), table_name='conversation_keys')
    op.drop_table('conversation_keys')
    # ### end Alembic commands ###
